export const FORGOT_ACCOUNT_PASSWORD = "FORGOT_ACCOUNT_PASSWORD"
export const FORGOT_ACCOUNT_PASSWORD_SUCCESS = "FORGOT_ACCOUNT_PASSWORD_SUCCESS"
export const FORGOT_ACCOUNT_PASSWORD_FAILURE = "FORGOT_ACCOUNT_PASSWORD_FAILURE"

