export const GET_BLOG_LIST = 'GET_BLOG_LIST'
export const GET_BLOG_LIST_SUCCESS = 'GET_BLOG_LIST_SUCCESS'
export const GET_BLOG_LIST_FAILURE = 'GET_BLOG_LIST_FAILURE'
export const GET_BLOG = 'GET_BLOG'
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS"
export const GET_BLOG_FAILURE = "GET_BLOG_FAILURE"

export const COMMENT_ON_BLOG = "COMMENT_ON_BLOG"
export const COMMENT_ON_BLOG_SUCCESS = "COMMENT_ON_BLOG_SUCCESS"
export const COMMENT_ON_BLOG_FAILURE = "COMMENT_ON_BLOG_FAILURE"

export const GET_BLOG_CATEGORIES = "GET_BLOG_CATEGORIES"
export const GET_BLOG_CATEGORIES_SUCCESS = "GET_BLOG_CATEGORIES_SUCCESS"
export const GET_BLOG_CATEGORIES_FAILURE = "GET_BLOG_CATEGORIES_FAILURE"

export const GET_BLOG_COMMENTS = "GET_BLOG_COMMENTS"
export const GET_BLOG_COMMENTS_SUCCESS = "GET_BLOG_COMMENTS_SUCCESS"
export const GET_BLOG_COMMENTS_FAILURE = "GET_BLOG_COMMENTS_FAILURE"