export const SIGN_IN_WITH_GOOGLE = "SIGN_IN_WITH_GOOGLE"
export const SIGN_IN_WITH_GOOGLE_SUCCESS = "SIGN_IN_WITH_GOOGLE_SUCCESS"
export const SIGN_IN_WITH_GOOGLE_FAILURE = "SIGN_IN_WITH_GOOGLE_FAILURE"

