export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"


export const GET_USER_DATA = 'GET_USER_DATA'
export const  GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const  GET_USER_DATA_FAILURE = 'GET_USER_DATA_SUCCESS'