export const SET_USER = 'SET_USER'
export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const GET_CHAT_CONTACTS = 'GET_CHAT_CONTACTS'
export const SELECT_CHAT = 'SELECT_CHAT'
export const UPDATE_SELECT_CHAT = 'UPDATE_SELECT_CHAT'
export const SEND_MSG = 'SEND_MSG'
export const SAVE_NEW_MESSAGE = 'SAVE_NEW_MESSAGE'
export const ADD_PARTICIPANTS = 'ADD_PARTICIPANTS'
export const MESSAGE_SEEN = 'MESSAGE_SEEN'
export const MESSAGE_DELIVERED = 'MESSAGE_DELIVERED'
export const SOCKET_AUTHORIZED = 'SOCKET_AUTHORIZED'

export const GET_CHAT_CONTACTS_SUCCESS = 'GET_CHAT_CONTACTS_SUCCESS'
export const GET_CHAT_CONTACTS_FAILURE = 'GET_CHAT_CONTACTS_FAILURE'

export const AUTHORIZED_FAILURE = 'AUTHORIZED_FAILURE'
export const AUTHORIZED_SUCCESS = 'AUTHORIZED_SUCCESS'

export const API_ERROR = 'API_ERROR'
export const SET_ROOM_JOINED = 'SET_ROOM_JOINED'

export const GET_PREVIOUS_MESSAGES = 'GET_PREVIOUS_MESSAGES'
export const GET_PREVIOUS_MESSAGES_SUCCESS = 'GET_PREVIOUS_MESSAGES_SUCCESS'
export const GET_PREVIOUS_MESSAGES_FAILURE = 'GET_PREVIOUS_MESSAGES_FAILURE'

export const NEW_MESSAGE = 'NEW_MESSAGE'

export const UPDATE_CHAT_HEAD_MESSAGE = 'UPDATE_CHAT_HEAD_MESSAGE'

export const UPDATE_CHAT_PARTICIPANTS = 'UPDATE_CHAT_PARTICIPANTS'

export const DELETE_MESSAGES = "DELETE_MESSAGES"


