export const SET_USER = 'SET_USER'
export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const GET_CHAT_CONTACTS = 'GET_CHAT_CONTACTS'
export const SELECT_CHAT = 'SELECT_CHAT'
export const UPDATE_SELECT_CHAT = 'UPDATE_SELECT_CHAT'
export const SEND_MSG = 'SEND_MSG'
export const SAVE_NEW_MESSAGE = 'SAVE_NEW_MESSAGE'
export const MESSAGE_SEEN = 'MESSAGE_SEEN'
export const MESSAGE_DELIVERED = 'MESSAGE_DELIVERED'
export const SOCKET_AUTHORIZED = 'SOCKET_AUTHORIZED'

export const GET_CHAT_CONTACTS_SUCCESS = 'GET_CHAT_CONTACTS_SUCCESS'
export const GET_CHAT_CONTACTS_FAILURE = 'GET_CHAT_CONTACTS_FAILURE'

export const AUTHORIZED_FAILURE = 'AUTHORIZED_FAILURE'
export const AUTHORIZED_SUCCESS = 'AUTHORIZED_SUCCESS'

export const API_ERROR = 'API_ERROR'
export const SET_ROOM_JOINED = 'SET_ROOM_JOINED'

export const SET_PREVIOUS_MESSAGES_LOADING = 'SET_PREVIOUS_MESSAGES_LOADING'
export const GET_PREVIOUS_MESSAGES_SUCCESS = 'GET_PREVIOUS_MESSAGES_SUCCESS'
export const GET_PREVIOUS_MESSAGES_FAILURE = 'GET_PREVIOUS_MESSAGES_FAILURE'

export const NEW_MESSAGE = 'NEW_MESSAGE'

export const UPDATE_CHAT_HEAD_MESSAGE = 'UPDATE_CHAT_HEAD_MESSAGE'

export const UPDATE_CHAT_PARTICIPANTS = 'UPDATE_CHAT_PARTICIPANTS'

export const DELETE_MESSAGES = "DELETE_MESSAGES"


export const PLAY_NOTIFICATION_SOUND = "PLAY_NOTIFICATION_SOUND"
export const STOP_NOTIFICATION_SOUND = "STOP_NOTIFICATION_SOUND"

export const SET_NOTIFICATION_ENABLED = "SET_NOTIFICATION_ENABLED"
export const SET_NOTIFICATION_IDS = "SET_NOTIFICATION_IDS"
export const MUTE_CHAT_NOTIFICATION = "MUTE_CHAT_NOTIFICATION"
export const UNMUTE_CHAT_NOTIFICATION = "UNMUTE_CHAT_NOTIFICATION"

export const UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT"
export const ADD_DOCUMENT_TO_QUEUE = "ADD_DOCUMENT_TO_QUEUE"
export const UPDATE_DOCUMENT_PROGRESS = "UPDATE_DOCUMENT_PROGRESS"
export const CANCEL_DOCUMENT_UPLOAD = "CANCEL_DOCUMENT_UPLOAD"
export const REMOVE_DOCUMENT = "REMOVE_DOCUMENT"

export const GET_SELECT_CHAT_DOCUMENTS = "GET_SELECT_CHAT_DOCUMENTS"
export const GET_SELECT_CHAT_DOCUMENTS_SUCCESS = "GET_SELECT_CHAT_DOCUMENTS_SUCCESS"
export const GET_SELECT_CHAT_DOCUMENTS_FAILURE = "GET_SELECT_CHAT_DOCUMENTS_FAILURE"


export const UPDATE_ABOUT = "UPDATE_ABOUT"
export const UPDATE_ABOUT_SUCCESS = "UPDATE_ABOUT_SUCCESS"
export const UPDATE_ABOUT_FAILURE = "UPDATE_ABOUT_FAILURE"

export const GET_ALL_TEACHER_STUDENTS = "GET_ALL_TEACHER_STUDENTS"
export const GET_ALL_TEACHER_STUDENTS_SUCCESS = "GET_ALL_TEACHER_STUDENTS_SUCCESS"
export const GET_ALL_TEACHER_STUDENTS_FAILURE = "GET_ALL_TEACHER_STUDENTS_FAILURE"

export const CREATE_CHAT = "CREATE_CHAT"
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS"
export const CREATE_CHAT_FAILURE = "CREATE_CHAT_FAILURE"


export const ADD_PARTICIPANTS = 'ADD_PARTICIPANTS'
export const ADD_PARTICIPANTS_SUCCESS = 'ADD_PARTICIPANTS_SUCCESS'
export const ADD_PARTICIPANTS_FAILURE = 'ADD_PARTICIPANTS_FAILURE'

export const REMOVE_PARTICIPANTS = 'REMOVE_PARTICIPANTS'
export const REMOVE_PARTICIPANTS_SUCCESS = 'REMOVE_PARTICIPANTS_SUCCESS'
export const REMOVE_PARTICIPANTS_FAILURE = 'REMOVE_PARTICIPANTS_FAILURE'