
export const GET_EBOOKS = "GET_EBOOKS"
export const GET_EBOOKS_SUCCESS = "GET_EBOOKS_SUCCESS"
export const GET_EBOOKS_FAILURE = "GET_EBOOKS_FAILURE"


export const DOWNLOAD_EBOOK = "DOWNLOAD_EBOOK"
export const DOWNLOAD_EBOOK_SUCCESS = "DOWNLOAD_EBOOK_SUCCESS"
export const DOWNLOAD_EBOOK_FAILURE = "DOWNLOAD_EBOOK_FAILURE"

export const BUY_EBOOK = "BUY_EBOOK"
export const BUY_EBOOK_SUCCESS = "BUY_EBOOK_SUCCESS"
export const BUY_EBOOK_FAILURE = "BUY_EBOOK_FAILURE"