export const RESET_ACCOUNT_PASSWORD = "RESET_ACCOUNT_PASSWORD"
export const RESET_ACCOUNT_PASSWORD_SUCCESS = "RESET_ACCOUNT_PASSWORD_SUCCESS"
export const RESET_ACCOUNT_PASSWORD_FAILURE = "RESET_ACCOUNT_PASSWORD_FAILURE"

