
export const GET_TEACHER_UPCOMING_ASSIGNMENTS = 'GET_TEACHER_UPCOMING_ASSIGNMENTS'
export const GET_TEACHER_UPCOMING_ASSIGNMENTS_SUCCESS = 'GET_TEACHER_UPCOMING_ASSIGNMENTS_SUCCESS'
export const GET_TEACHER_UPCOMING_ASSIGNMENTS_FAILURE = 'GET_TEACHER_UPCOMING_ASSIGNMENTS_FAILURE'

export const GET_TEACHER_PAST_ASSIGNMENTS = 'GET_TEACHER_PAST_ASSIGNMENTS'
export const GET_TEACHER_PAST_ASSIGNMENTS_SUCCESS = 'GET_TEACHER_PAST_ASSIGNMENTS_SUCCESS'
export const GET_TEACHER_PAST_ASSIGNMENTS_FAILURE = 'GET_TEACHER_PAST_ASSIGNMENTS_FAILURE'

export const GET_STUDENT_ASSIGNMENTS = "GET_STUDENT_ASSIGNMENTS"
export const GET_STUDENT_ASSIGNMENTS_SUCCESS = "GET_STUDENT_ASSIGNMENTS_SUCCESS"
export const GET_STUDENT_ASSIGNMENTS_FAILURE = "GET_STUDENT_ASSIGNMENTS_FAILURE"

export const GET_TEACHER_ASSIGNMENTS = "GET_TEACHER_ASSIGNMENTS"
export const GET_TEACHER_ASSIGNMENTS_SUCCESS = "GET_TEACHER_ASSIGNMENTS_SUCCESS"
export const GET_TEACHER_ASSIGNMENTS_FAILURE = "GET_TEACHER_ASSIGNMENTS_FAILURE"


export const POST_ASSIGNMENT = "POST_ASSIGNMENT"
export const POST_ASSIGNMENT_SUCCESS = "POST_ASSIGNMENT_SUCCESS"
export const POST_ASSIGNMENT_FAILURE = "POST_ASSIGNMENT_FAILURE"


export const PUT_ASSIGNMENT = "PUT_ASSIGNMENT"
export const PUT_ASSIGNMENT_SUCCESS = "PUT_ASSIGNMENT_SUCCESS"
export const PUT_ASSIGNMENT_FAILURE = "PUT_ASSIGNMENT_FAILURE"

export const ASSIGN_ASSIGNMENT = "ASSIGN_ASSIGNMENT"
export const ASSIGN_ASSIGNMENT_SUCCESS = "ASSIGN_ASSIGNMENT_SUCCESS"
export const ASSIGN_ASSIGNMENT_FAILURE = "ASSIGN_ASSIGNMENT_FAILURE"


export const GET_ASSIGNMENT_PAST_STUDENT = "GET_ASSIGNMENT_PAST_STUDENT"
export const GET_ASSIGNMENT_PAST_STUDENT_SUCCESS = "GET_ASSIGNMENT_PAST_STUDENT_SUCCESS"
export const GET_ASSIGNMENT_PAST_STUDENT_FAILURE = "GET_ASSIGNMENT_PAST_STUDENT_FAILURE"


export const GET_ASSIGNMENT_UPCOMING_STUDENT = "GET_ASSIGNMENT_UPCOMING_STUDENT"
export const GET_ASSIGNMENT_UPCOMING_STUDENT_SUCCESS = "GET_ASSIGNMENT_UPCOMING_STUDENT_SUCCESS"
export const GET_ASSIGNMENT_UPCOMING_STUDENT_FAILURE = "GET_ASSIGNMENT_UPCOMING_STUDENT_FAILURE"


export const UNASSIGN_ASSIGNMENT = "UNASSIGN_ASSIGNMENT"
export const UNASSIGN_ASSIGNMENT_SUCCESS = "UNASSIGN_ASSIGNMENT_SUCCESS"
export const UNASSIGN_ASSIGNMENT_FAILURE = "UNASSIGN_ASSIGNMENT_FAILURE"