
export const GET_TEST_ATTEMPTS = "GET_TEST_ATTEMPTS"
export const GET_TEST_ATTEMPTS_SUCCESS = "GET_TEST_ATTEMPTS_SUCCESS"
export const GET_TEST_ATTEMPTS_FAILURE = "GET_TEST_ATTEMPTS_FAILURE"


export const GET_ATTEMPT_DETAIL = "GET_ATTEMPT_DETAIL"
export const GET_ATTEMPT_DETAIL_SUCCESS = "GET_ATTEMPT_DETAIL_SUCCESS"
export const GET_ATTEMPT_DETAIL_FAILURE = "GET_ATTEMPT_DETAIL_FAILURE"

export const GET_TEST_DETAIL = "GET_TEST_DETAIL"
export const GET_TEST_DETAIL_SUCCESS = "GET_TEST_DETAIL_SUCCESS"
export const GET_TEST_DETAIL_FAILURE = "GET_TEST_DETAIL_FAILURE"


export const PUT_SUBJECTIVE_ATTEMPT_MARKS = "PUT_SUBJECTIVE_ATTEMPT_MARKS"
export const PUT_SUBJECTIVE_ATTEMPT_MARKS_SUCCESS = "PUT_SUBJECTIVE_ATTEMPT_MARKS_SUCCESS"
export const PUT_SUBJECTIVE_ATTEMPT_MARKS_FAILURE = "PUT_SUBJECTIVE_ATTEMPT_MARKS_FAILURE"