export const GET_ALL_MEETINGS = 'GET_ALL_MEETINGS'
export const GET_ALL_MEETINGS_SUCCESS = 'GET_ALL_MEETINGS_SUCCESS'
export const GET_ALL_MEETINGS_ERROR = 'GET_ALL_MEETINGS_ERROR'

export const GET_MEETING_DATES = 'GET_MEETING_DATES'
export const GET_MEETING_DATES_SUCCESS = 'GET_MEETING_DATES_SUCCESS'
export const GET_MEETING_DATES_FAILURE = 'GET_MEETING_DATES_FAILURE'

export const NEW_MEETING = 'NEW_MEETING'
export const NEW_MEETING_SUCCESS = 'NEW_MEETING_SUCCESS'
export const NEW_MEETING_FAILURE = 'NEW_MEETING_FAILURE'

export const UPDATE_MEETING = 'UPDATE_MEETING'
export const UPDATE_MEETING_SUCCESS = 'UPDATE_MEETING_SUCCESS'
export const UPDATE_MEETING_FAILURE = 'UPDATE_MEETING_FAILURE'

export const GET_STUDENTS_FOR_MEETING = 'GET_STUDENTS_FOR_MEETING'
export const GET_STUDENTS_FOR_MEETING_SUCCESS = 'GET_STUDENTS_FOR_MEETING_SUCCESS'
export const GET_STUDENTS_FOR_MEETING_FAILURE = 'GET_STUDENTS_FOR_MEETING_FAILURE'

export const GET_MEETING_TOKEN = 'GET_MEETING_TOKEN'
export const GET_MEETING_TOKEN_SUCCESS = 'GET_MEETING_TOKEN_SUCCESS'
export const GET_MEETING_TOKEN_FAILURE = 'GET_MEETING_TOKEN_FAILURE'
