export const GET_ASSIGNMENT_ATTEMPTS = "GET_ASSIGNMENT_ATTEMPTS"
export const GET_ASSIGNMENT_ATTEMPTS_SUCCESS = "GET_ASSIGNMENT_ATTEMPTS_SUCCESS"
export const GET_ASSIGNMENT_ATTEMPTS_FAILURE = "GET_ASSIGNMENT_ATTEMPTS_FAILURE"

export const GET_ASSIGNMENT_ATTEMPT_DETAIL = "GET_ASSIGNMENT_ATTEMPT_DETAIL"
export const GET_ASSIGNMENT_ATTEMPT_DETAIL_SUCCESS = "GET_ASSIGNMENT_ATTEMPT_DETAIL_SUCCESS"
export const GET_ASSIGNMENT_ATTEMPT_DETAIL_FAILURE = "GET_ASSIGNMENT_ATTEMPT_DETAIL_FAILURE"

export const GET_ASSIGNMENT_DETAIL = "GET_ASSIGNMENT_DETAIL"
export const GET_ASSIGNMENT_DETAIL_SUCCESS = "GET_ASSIGNMENT_DETAIL_SUCCESS"
export const GET_ASSIGNMENT_DETAIL_FAILURE = "GET_ASSIGNMENT_DETAIL_FAILURE"