export const GET_TEACHER_TOPICS = 'GET_TEACHER_TOPICS'
export const GET_TEACHER_TOPICS_SUCCESS = 'GET_TEACHER_TOPICS_SUCCESS'
export const GET_TEACHER_TOPICS_FAILURE = 'GET_TEACHER_TOPICS_FAILURE'

export const GET_TEACHER_RECENT_LESSONS = 'GET_TEACHER_RECENT_LESSONS'
export const GET_TEACHER_RECENT_LESSONS_SUCCESS = 'GET_TEACHER_RECENT_LESSONS_SUCCESS'
export const GET_TEACHER_RECENT_LESSONS_FAILURE = 'GET_TEACHER_RECENT_LESSONS_FAILURE'

export const GET_TEACHER_TOPIC_LESSONS = 'GET_TEACHER_TOPIC_LESSONS'
export const GET_TEACHER_TOPIC_LESSONS_SUCCESS = 'GET_TEACHER_TOPIC_LESSONS_SUCCESS'
export const GET_TEACHER_TOPIC_LESSONS_FAILURE = 'GET_TEACHER_TOPIC_LESSONS_FAILURE'

export const SELECT_TOPIC = 'SELECT_TOPIC'
export const SELECT_LESSON = 'SELECT_LESSON'

export const ADD_NEW_TOPIC = 'ADD_NEW_TOPIC'
export const ADD_NEW_TOPIC_SUCCESS = 'ADD_NEW_TOPIC_SUCCESS'
export const ADD_NEW_TOPIC_FAILURE = 'ADD_NEW_TOPIC_FAILURE'

export const ADD_NEW_LESSON = 'ADD_NEW_TOPIC_LESSON'
export const ADD_NEW_LESSON_SUCCESS = 'ADD_NEW_LESSON_SUCCESS'
export const ADD_NEW_LESSON_FAILURE = 'ADD_NEW_LESSON_FAILURE'


export const GET_LESSON = 'GET_LESSON'
export const GET_LESSON_SUCCESS = 'GET_LESSON_SUCCESS'
export const GET_LESSON_FAILURE = 'GET_LESSON_FAILURE'

export const GET_STUDENTS_FOR_LESSON = 'GET_STUDENTS_FOR_LESSON'
export const GET_STUDENTS_FOR_LESSON_SUCCESS = 'GET_STUDENTS_FOR_LESSON_SUCCESS'
export const GET_STUDENTS_FOR_LESSON_FAILURE = 'GET_STUDENTS_FOR_LESSON_FAILURE'


export const ASSIGN_LESSON_TO_STUDENTS = 'ASSIGN_LESSON_TO_STUDENTS'
export const ASSIGN_LESSON_TO_STUDENTS_SUCCESS = 'ASSIGN_LESSON_TO_STUDENTS_SUCCESS'
export const ASSIGN_LESSON_TO_STUDENTS_FAILURE = 'ASSIGN_LESSON_TO_STUDENTS_FAILURE'

export const UNASSIGN_LESSON_TO_STUDENTS = 'UNASSIGN_LESSON_TO_STUDENTS'
export const UNASSIGN_LESSON_TO_STUDENTS_SUCCESS = 'UNASSIGN_LESSON_TO_STUDENTS_SUCCESS'
export const UNASSIGN_LESSON_TO_STUDENTS_FAILURE = 'UNASSIGN_LESSON_TO_STUDENTS_FAILURE'