export const GET_USER_DOCUMENTS = 'GET_USER_DOCUMENTS'
export const GET_USER_DOCUMENTS_SUCCESS = 'GET_USER_DOCUMENTS_SUCCESS'
export const GET_USER_DOCUMENTS_FAILURE = 'GET_USER_DOCUMENTS_FAILURE'
export const SELECT_USER_DOCUMENTS_TYPE = 'SELECT_USER_DOCUMENTS_TYPE'


export const UPLOAD_USER_DOCUMENT = "UPLOAD_USER_DOCUMENT"
export const ADD_USER_DOCUMENT_TO_QUEUE = "ADD_USER_DOCUMENT_TO_QUEUE"
export const UPDATE_USER_DOCUMENT_PROGRESS = "UPDATE_USER_DOCUMENT_PROGRESS"
export const CANCEL_USER_DOCUMENT_UPLOAD = "CANCEL_USER_DOCUMENT_UPLOAD"


export const DELETE_USER_DOCUMENT = "DELETE_USER_DOCUMENT"
export const DELETE_USER_DOCUMENT_SUCCESS = "DELETE_USER_DOCUMENT_SUCCESS"
export const DELETE_USER_DOCUMENT_FAILURE = "DELETE_USER_DOCUMENT_FAILURE"