export const GET_STRIPE_PUBLIC_KEY = "GET_STRIPE_PUBLIC_KEY"
export const GET_STRIPE_PUBLIC_KEY_SUCCESS = "GET_STRIPE_PUBLIC_KEY_SUCCESS"
export const GET_STRIPE_PUBLIC_KEY_FAILURE = "GET_STRIPE_PUBLIC_KEY_FAILURE"

export const GET_PAYMENT_METHODS = "GET_PAYMENT_METHODS"
export const GET_PAYMENT_METHODS_SUCCESS = "GET_PAYMENT_METHODS_SUCCESS"
export const GET_PAYMENT_METHODS_FAILURE = "GET_PAYMENT_METHODS_FAILURE"

export const POST_PAYMENT_METHODS = "POST_PAYMENT_METHODS"
export const POST_PAYMENT_METHODS_SUCCESS = "POST_PAYMENT_METHODS_SUCCESS"
export const POST_PAYMENT_METHODS_FAILURE = "POST_PAYMENT_METHODS_FAILURE"


export const SET_DEFAULT_PAYMENT_METHOD = "SET_DEFAULT_PAYMENT_METHOD"
export const SET_DEFAULT_PAYMENT_METHOD_SUCCESS = "SET_DEFAULT_PAYMENT_METHOD_SUCCESS"
export const SET_DEFAULT_PAYMENT_METHOD_FAILURE = "SET_DEFAULT_PAYMENT_METHOD_FAILURE"

export const GET_PAYMENT_PLAN = "GET_PAYMENT_PLAN"
export const GET_PAYMENT_PLAN_SUCCESS = "GET_PAYMENT_PLAN_SUCCESS"
export const GET_PAYMENT_PLAN_FAILURE = "GET_PAYMENT_PLAN_FAILURE"

export const POST_PAYMENT = "POST_PAYMENT"
export const POST_PAYMENT_SUCCESS = "POST_PAYMENT_SUCCESS"
export const POST_PAYMENT_FAILURE = "POST_PAYMENT_FAILURE"

export const DELETE_PAYMENT_METHOD = "DELETE_PAYMENT_METHOD"
export const DELETE_PAYMENT_METHOD_SUCCESS = "DELETE_PAYMENT_METHOD_SUCCESS"
export const DELETE_PAYMENT_METHOD_FAILURE = "DELETE_PAYMENT_METHOD_FAILURE"