export const IOEvents = {
    CONNECT: "CONNECT",
    DISCONNECT: "disconnect",
    AUTHORIZATION: "AUTHORIZATION",
    SET_LANGUAGE: "SET_LANGUAGE",
    NEW_MESSAGE: "NEW_MESSAGE",
    UPDATE_MESSAGE: "UPDATE_MESSAGE",
    ADD_PARTICIPANT: "ADD_PARTICIPANT",
    REMOVE_PARTICIPANT: "REMOVE_PARTICIPANT",
    GET_PREVIOUS_MESSAGES: "GET_PREVIOUS_MESSAGES",
    JOIN_ROOM: "JOIN_ROOM",
    JOIN_GLOBAL_ROOM: "JOIN_GLOBAL_ROOM",
    GLOBAL_ROOM_NOTIFICATION: "GLOBAL_ROOM_NOTIFICATION",
    MESSAGES_DELIVERED: "MESSAGES_DELIVERED",
    MESSAGES_SEEN: "MESSAGES_SEEN",
    MESSAGES_DELETE: "MESSAGES_DELETE",
    BLOCK_CHAT: "BLOCK_CHAT",
    UNBLOCK_CHAT: "UNBLOCK_CHAT"
};