
export const GET_STUDENTS = "GET_STUDENTS"
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS"
export const GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE"

export const GET_STUDENT_BY_ID = "GET_STUDENT_BY_ID"
export const GET_STUDENT_BY_ID_SUCCESS = "GET_STUDENT_BY_ID_SUCCESS"
export const GET_STUDENT_BY_ID_FAILURE = "GET_STUDENT_BY_ID_FAILURE"


export const GET_STUDENT_ATTEMPTS = "GET_STUDENT_ATTEMPTS"