export const SETUP_ACCOUNT_PASSWORD = "SETUP_ACCOUNT_PASSWORD"
export const SETUP_ACCOUNT_PASSWORD_SUCCESS = "SETUP_ACCOUNT_PASSWORD_SUCCESS"
export const SETUP_ACCOUNT_PASSWORD_FAILURE = "SETUP_ACCOUNT_PASSWORD_FAILURE"

