export const UPLOAD_PROFILE_PICTURE = 'UPLOAD_PROFILE_PICTURE'
export const UPLOAD_PROFILE_PICTURE_SUCCESS = 'UPLOAD_PROFILE_PICTURE_SUCCESS'
export const UPLOAD_PROFILE_PICTURE_FAILURE = 'UPLOAD_PROFILE_PICTURE_FAILURE'

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA'
export const UPDATE_PROFILE_DATA_SUCCESS = 'UPDATE_PROFILE_DATA_SUCCESS'
export const UPDATE_PROFILE_DATA_FAILURE = 'UPDATE_PROFILE_DATA_FAILURE'

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const SET_PROFILE_USER = 'SET_PROFILE_USER'

export const GET_COUNTIES = ' GET_COUNTIES'
export const  GET_COUNTIES_SUCCESS = 'GET_COUNTIES_SUCCESS'
export const  GET_COUNTIES_FAILURE = 'GET_COUNTIES_SUCCESS'

