
export const GET_STUDENT_TESTS = "GET_STUDENT_TESTS"
export const GET_STUDENT_TESTS_SUCCESS = "GET_STUDENT_TESTS_SUCCESS"
export const GET_STUDENT_TESTS_FAILURE = "GET_STUDENT_TESTS_FAILURE"

export const GET_TEACHER_TESTS = "GET_TEACHER_TESTS"
export const GET_TEACHER_TESTS_SUCCESS = "GET_TEACHER_TESTS_SUCCESS"
export const GET_TEACHER_TESTS_FAILURE = "GET_TEACHER_TESTS_FAILURE"


export const POST_TEST = "POST_TEST"
export const POST_TEST_SUCCESS = "POST_TEST_SUCCESS"
export const POST_TEST_FAILURE = "POST_TEST_FAILURE"


export const PUT_TEST = "PUT_TEST"
export const PUT_TEST_SUCCESS = "PUT_TEST_SUCCESS"
export const PUT_TEST_FAILURE = "PUT_TEST_FAILURE"