
export const GET_TEACHER_UPCOMING_TESTS = 'GET_TEACHER_UPCOMING_TESTS'
export const GET_TEACHER_UPCOMING_TESTS_SUCCESS = 'GET_TEACHER_UPCOMING_TESTS_SUCCESS'
export const GET_TEACHER_UPCOMING_TESTS_FAILURE = 'GET_TEACHER_UPCOMING_TESTS_FAILURE'

export const GET_TEACHER_PAST_TESTS = 'GET_TEACHER_PAST_TESTS'
export const GET_TEACHER_PAST_TESTS_SUCCESS = 'GET_TEACHER_PAST_TESTS_SUCCESS'
export const GET_TEACHER_PAST_TESTS_FAILURE = 'GET_TEACHER_PAST_TESTS_FAILURE'


export const GET_STUDENT_TESTS = "GET_STUDENT_TESTS"
export const GET_STUDENT_TESTS_SUCCESS = "GET_STUDENT_TESTS_SUCCESS"
export const GET_STUDENT_TESTS_FAILURE = "GET_STUDENT_TESTS_FAILURE"

export const GET_TEACHER_TESTS = "GET_TEACHER_TESTS"
export const GET_TEACHER_TESTS_SUCCESS = "GET_TEACHER_TESTS_SUCCESS"
export const GET_TEACHER_TESTS_FAILURE = "GET_TEACHER_TESTS_FAILURE"


export const POST_TEST = "POST_TEST"
export const POST_TEST_SUCCESS = "POST_TEST_SUCCESS"
export const POST_TEST_FAILURE = "POST_TEST_FAILURE"


export const PUT_TEST = "PUT_TEST"
export const PUT_TEST_SUCCESS = "PUT_TEST_SUCCESS"
export const PUT_TEST_FAILURE = "PUT_TEST_FAILURE"

export const ASSIGN_TEST = "ASSIGN_TEST"
export const ASSIGN_TEST_SUCCESS = "ASSIGN_TEST_SUCCESS"
export const ASSIGN_TEST_FAILURE = "ASSIGN_TEST_FAILURE"


export const GET_PAST_STUDENT = "GET_PAST_STUDENT"
export const GET_PAST_STUDENT_SUCCESS = "GET_PAST_STUDENT_SUCCESS"
export const GET_PAST_STUDENT_FAILURE = "GET_PAST_STUDENT_FAILURE"


export const GET_UPCOMING_STUDENT = "GET_UPCOMING_STUDENT"
export const GET_UPCOMING_STUDENT_SUCCESS = "GET_UPCOMING_STUDENT_SUCCESS"
export const GET_UPCOMING_STUDENT_FAILURE = "GET_UPCOMING_STUDENT_FAILURE"


export const UNASSIGN_TEST = "UNASSIGN_TEST"
export const UNASSIGN_TEST_SUCCESS = "UNASSIGN_TEST_SUCCESS"
export const UNASSIGN_TEST_FAILURE = "UNASSIGN_TEST_FAILURE"


export const GET_TEST_BY_ID = "GET_TEST_BY_ID"
export const GET_TEST_BY_ID_SUCCESS = "GET_TEST_BY_ID_SUCCESS"
export const GET_TEST_BY_ID_FAILURE = "GET_TEST_BY_ID_FAILURE"