
export const GET_STUDENT_TESTS = "GET_STUDENT_TESTS"
export const GET_STUDENT_TESTS_SUCCESS = "GET_STUDENT_TESTS_SUCCESS"
export const GET_STUDENT_TESTS_FAILURE = "GET_STUDENT_TESTS_FAILURE"

export const GET_TEACHER_TESTS = "GET_TEACHER_TESTS"
export const GET_TEACHER_TESTS_SUCCESS = "GET_TEACHER_TESTS_SUCCESS"
export const GET_TEACHER_TESTS_FAILURE = "GET_TEACHER_TESTS_FAILURE"